#!/bin/bash

if [ "$QC_ENABLE_SONGDB" = "Y" ]; then
cat >>conf.pri <<EOT

### Enable OpenRadio SongDB support
DEFINES += ENABLE_SONGDB
CONFIG += songdb
EOT
fi

if [ "$QC_ENABLE_HWMIXER" = "Y" ]; then
cat >>conf.pri <<EOT

### Enable OpenRadio harware mixer device support
DEFINES += ENABLE_HWMIXER
CONFIG += hwmixer
EOT
fi
